config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  devise_for :users

  root 'posts#index'

  # add this line to link tags to posts with the respective tag
  get 'tags/:tag', to: 'posts#index', as: :tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def get_user(comment)
    @user = User.find(comment.user_id)['email']
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
  validate :unique_to_day

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def get_username(email)
    email.split('@', 0)[0]
  end

  private

  def unique_to_day
    title = self[:title]

    unless Post.where('title = ? AND created_at > ?', title, Time.now.beginning_of_day).empty?
      errors.add(:title, 'already posted today')
    end
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index; end

  # GET /comments/1
  # GET /comments/1.json
  def show; end

  # GET /comments/new
  def new; end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to post_path(@post), notice: @comment.errors }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  helper_method :sort_column, :sort_direction

  # GET /posts
  # GET /posts.json
  def index
    if params[:keyword]
      term = params[:keyword]
      @posts = Post.where('lower(body) LIKE lower(?)', "%#{term}%")
      redirect_to posts_url, notice: 'No matches!' if @posts.count == 0
    elsif params[:sort]
      @posts = Post.order(sort_column + ' ' + sort_direction)
    else
      @posts = params[:tag] ? Post.tagged_with(params[:tag]) : Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Post.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }, class: css_class
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>
  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form', comment: @comment %>
<%= link_to 'Back', root_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>
<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>
<%= link_to 'Edit', edit_post_comment_path(@comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodayIHave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='container'>
      <nav class="navbar navbar-light justify-content-right blue-grey lighten-5 mb-4" style="background-color: #e3f2fd;">
        <ul class="nav justify-content-right">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class:'btn btn-outline-success' %>
          </li>
          <% if current_user %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'btn btn-outline-dark' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:'btn btn-outline-success' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:'btn btn-outline-success' %>
            </li>
          <% end %>
          <%= form_tag posts_url, method: :get, class:"form-inline ml-auto"  do %>
            <div class="md-form my-0">
              <%= text_field_tag :keyword, params[:keyword], placeholder: "Search posts...", class:"form-control" %>
              <%= submit_tag 'Search', name: nil, class:"btn btn-outline-white btn-md my-0 ml-sm-2" %>
            </div>
          <% end %>
        </ul>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>
<script>
  $(document).on('ready page:load', function () {
    $('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, url: posts_path, local: true, html: { class: 'form-group' }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true}%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Updates</h1>
<table class='table-striped '>
  <thead class='thead-dark'>
    <tr>
      <th><%= sortable "title" %></th>
      <th><%= sortable "body" %></th>
      <th><%= sortable "user_id" %></th>
      <th><%= sortable "created_at" %></th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body.slice!(0,10)+"..." %></td>
        <td><%= post.get_username(post.user.email) %></td>
        <td><%= time_ago_in_words(post.created_at) %></td>
        <td><small> <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></td>
        <td><%= link_to 'Show', post, class:'btn btn-light' %></td>
        <% if post.user == current_user %>
          <td><%= link_to 'Edit', edit_post_path(post), class:'btn btn-light' %></td>
          <td><%= button_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Post', new_post_path, class:'btn btn-light' %>

app/views/posts/new.html.erb
<h1>New Update</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<p>
  <small>Tags: <%= raw @post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small>
</p>
<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>
<% if @post.user == current_user %>
  <%= link_to 'Edit', edit_post_path(@post), class:'btn btn-light' %>
  <%= button_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
<% end %>
<hr>
<h2>Comments:</h2>
<% @post.comments.each do |comment| %>
  <strong>Comment: </strong><br>
  <%= comment.comment %><br>
  <strong>by: </strong>
  <%= comment.get_user(comment) %><br>
  <br>
<% end %>
<br>
<hr>
<h2>Add Comment:</h2>
<%= render 'comments/form' %>
<br>
<%= link_to 'Back', posts_path, class:'btn btn-light' %>